---
- name: API Deployment Setup
  hosts: 192.168.1.201
  tasks:
    - name: Push to DockerHub
      shell: |
        docker push marcuskielman/devops_api: latest
        docker image rm marcuskielman/devops_api
    - name: Remove Production
      shell: rm -rf /home/marcus/production/*
      ignore_errors: True
    - name: Go to Production
      shell: mv /home/marcus/staging/devops-api-2/ /home/marcus/production/
    - name: Check for existing Pods and Replace
      shell: |
        kubectl get pods -o name --context kind-devops-api | grep mariadb
      register: deployed
      ignore_errors: True
    - name: Replace API Pods
      shell: |
        cd /home/marcus/production/devops-api-2/terraform_modules/default_api
        terraform refresh
      when: deployed.stdout != ""
    - name: Set Up Kubernetes Deployment
      shell: |
        cd /home/marcus/production/devops-api-2/terraform_modules/default_api
        terraform init
        echo "yes" | terraform apply
        kubectl get pods --context kind-devops-api -o name | grep mariadb
      register: mariadb
      when: deployed.stdout == ""
    - name: Configure Database
      shell: |
        echo "source /usr/src/app/mysqlsampledatabase.sql" | kubectl exec -i {{ mariadb.stdout_lines[0] }} --context kind-devops-api -- mysql -uroot -proot classicmodels
      when: deployed.stdout == ""

